export const pdfConfig = {
  A01: {
    visApplicantTxtE: true,
    visApplicantE: true,
    visHrCompE: true,
    visHrDeptE: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,

    visApplyAmount: true,
    visCurrency: true
  },
  A02: {
    visApplicantTxtE: true,
    visApplicantE: true,
    visHrCompE: true,
    visHrDeptE: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,
    visInvoiceCategory: true,

    visReimbAmount: true,
    visVerifyAmount: true,
    visPaymentAmount: true,
    visCurrency: true

  },

  B01: {
    visApplicantTxtE: true,
    visApplicantE: true,
    visHrCompE: true,
    visHrDeptE: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,
    visLoanType: true,

    visLoanAmount: true,
    visCurrency: true
  },
  B02: {
    visApplicantTxtE: true,
    visApplicantE: true,
    visHrCompE: true,
    visHrDeptE: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,
    visLoanType: true,

    visLoanAmount: true,
    visCurrency: true
  },
  B03: {
    visApplicantTxtV: true,
    visApplicantV: true,
    visHrCompV: true,
    visHrDeptV: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,
    visInvoiceCategory: true,

    visPayAmount: true,
    visVerifyAmount: true,
    visPaymentAmount: true,
    visCurrency: true,
    visContract: true,
    visPayee: true
  },
  B04: {
    visApplicantTxtV: true,
    visApplicantV: true,
    visHrCompV: true,
    visHrDeptV: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,
    visInvoiceCategory: true,

    visPayAmount: true,
    visVerifyAmount: true,
    visPaymentAmount: true,
    visCurrency: true,
    visContract: true,
    visPayee: true
  },
  C01: {
    visApplicantTxtV: true,
    visApplicantV: true,
    visHrCompV: true,
    visHrDeptV: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,
    visInvoiceCategory: true,

    visPayAmount: true,
    visVerifyAmount: true,
    visPaymentAmount: true,
    visCurrency: true,
    visContract: true,
    visPayee: true
  },
  C02: {
    visApplicantTxtV: true,
    visApplicantV: true,
    visHrCompV: true,
    visHrDeptV: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,
    visInvoiceCategory: true,

    visPayAmount: true,
    visVerifyAmount: true,
    visPaymentAmount: true,
    visCurrency: true,
    visContract: true,
    visPayee: true
  },
  D01: {
    visApplicantTxtV: true,
    visApplicantV: true,
    visHrCompV: true,
    visHrDeptV: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,
    visInvoiceCategory: true,

    visPayAmount: true,
    visCurrency: true
  },
  D02: {
    visApplicantTxtV: true,
    visApplicantV: true,
    visHrCompV: true,
    visHrDeptV: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,

    visUnFreezeAmount: true,
    visCurrency: true
  },
  EX01: {
    visApplicantTxtV: true,
    visApplicantV: true,
    visHrCompV: true,
    visHrDeptV: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,

    visCurrency: true,
    visRefundAmount: true
  },
  EX02: {
    visApplicantTxtV: true,
    visApplicantV: true,
    visHrCompV: true,
    visHrDeptV: true,
    visCostComp: true,
    visCostDept: true,
    visBusPlate: true,
    visProject: true,
    visProcType: true,
    visProcSubType: true,

    visCurrency: true,
    visRefundAmount: true
  }
}
