export const stampTax = {
  stampId: '',
  cpnCode: '',
  regDate: '',
  contractNo: '',
  partnerName: '',
  settlementAmount: '',
  taxaction: '',
  taxRate: 0,
  amount: '',
  jtflag: '',
  rource: '',
  document: '',
  accountDocument: '',
  creater: '',
  createDate: null,
  updateDate: null,
  revisor: '',
  memo: '',
  cpnName: '',
  partnerCode: '',
  createrName: '',
  revisorName: ''

}
